/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.pcm.confidentiality.context;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ConfidentialityContextDSLStandaloneSetup extends ConfidentialityContextDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new ConfidentialityContextDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
