/**
 */
package org.palladiosimulator.pcm.confidentiality.context.model.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.pcm.confidentiality.context.model.util.ModelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelItemProviderAdapterFactory extends ModelAdapterFactory
        implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public ModelItemProviderAdapterFactory() {
        supportedTypes.add(IEditingDomainItemProvider.class);
        supportedTypes.add(IStructuredItemContentProvider.class);
        supportedTypes.add(ITreeItemContentProvider.class);
        supportedTypes.add(IItemLabelProvider.class);
        supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.pcm.confidentiality.context.model.HierarchicalContext} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected HierarchicalContextItemProvider hierarchicalContextItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.pcm.confidentiality.context.model.HierarchicalContext}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createHierarchicalContextAdapter() {
        if (hierarchicalContextItemProvider == null) {
            hierarchicalContextItemProvider = new HierarchicalContextItemProvider(this);
        }

        return hierarchicalContextItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.pcm.confidentiality.context.model.SingleAttributeContext} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SingleAttributeContextItemProvider singleAttributeContextItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.pcm.confidentiality.context.model.SingleAttributeContext}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSingleAttributeContextAdapter() {
        if (singleAttributeContextItemProvider == null) {
            singleAttributeContextItemProvider = new SingleAttributeContextItemProvider(this);
        }

        return singleAttributeContextItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.pcm.confidentiality.context.model.RelatedContextSet} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RelatedContextSetItemProvider relatedContextSetItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.pcm.confidentiality.context.model.RelatedContextSet}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createRelatedContextSetAdapter() {
        if (relatedContextSetItemProvider == null) {
            relatedContextSetItemProvider = new RelatedContextSetItemProvider(this);
        }

        return relatedContextSetItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.pcm.confidentiality.context.model.ContextContainer} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ContextContainerItemProvider contextContainerItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.pcm.confidentiality.context.model.ContextContainer}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createContextContainerAdapter() {
        if (contextContainerItemProvider == null) {
            contextContainerItemProvider = new ContextContainerItemProvider(this);
        }

        return contextContainerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.pcm.confidentiality.context.model.ContextType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ContextTypeItemProvider contextTypeItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.pcm.confidentiality.context.model.ContextType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createContextTypeAdapter() {
        if (contextTypeItemProvider == null) {
            contextTypeItemProvider = new ContextTypeItemProvider(this);
        }

        return contextTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.pcm.confidentiality.context.model.TypeContainer} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TypeContainerItemProvider typeContainerItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.pcm.confidentiality.context.model.TypeContainer}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTypeContainerAdapter() {
        if (typeContainerItemProvider == null) {
            typeContainerItemProvider = new TypeContainerItemProvider(this);
        }

        return typeContainerItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public boolean isFactoryForType(Object type) {
        return supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter adapt(Notifier notifier, Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Object adapt(Object object, Object type) {
        if (isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void addListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void removeListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void fireNotifyChanged(Notification notification) {
        changeNotifier.fireNotifyChanged(notification);

        if (parentAdapterFactory != null) {
            parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void dispose() {
        if (hierarchicalContextItemProvider != null)
            hierarchicalContextItemProvider.dispose();
        if (singleAttributeContextItemProvider != null)
            singleAttributeContextItemProvider.dispose();
        if (relatedContextSetItemProvider != null)
            relatedContextSetItemProvider.dispose();
        if (contextContainerItemProvider != null)
            contextContainerItemProvider.dispose();
        if (contextTypeItemProvider != null)
            contextTypeItemProvider.dispose();
        if (typeContainerItemProvider != null)
            typeContainerItemProvider.dispose();
    }

}
