/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.pcm.confidentiality.context.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.pcm.confidentiality.context.ConfidentialityContextDSLRuntimeModule;
import org.palladiosimulator.pcm.confidentiality.context.ConfidentialityContextDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConfidentialityContextDSLIdeSetup extends ConfidentialityContextDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConfidentialityContextDSLRuntimeModule(), new ConfidentialityContextDSLIdeModule()));
	}
	
}
