/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.pcm.confidentiality.context.ide;


/**
 * Use this class to register ide components.
 */
public class ConfidentialityContextDSLIdeModule extends AbstractConfidentialityContextDSLIdeModule {
}
