/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.pcm.confidentiality.context.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ConfidentialityContextDSLUiModule extends AbstractConfidentialityContextDSLUiModule {

	public ConfidentialityContextDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
